import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { api } from '../../api/client'
import { apiErrorMessage } from '../../api/errors'
import { PermissionGate } from '../../auth/PermissionGate'
import { ResourceTable } from '../../components/tables/ResourceTable'
import { Modal } from '../../components/ui/Modal'
import { PageHeader } from '../../components/ui/PageHeader'
import type { Paginated } from '../../types/api'

interface Movement { id: number; tipo: string; referencia: string; sucursal: number; almacen_origen: number | null; almacen_destino: number | null; created_at: string }
interface Option { id: number; nombre?: string; razon_social?: string; codigo?: string }
interface Item { producto_id: string; unidad_medida_id: string; cantidad: string; costo_unitario: string }
const labels: Record<string, string> = { purchase: 'Compra', output: 'Salida', transfer: 'Traslado', adjustment: 'Ajuste' }
const emptyItem = (): Item => ({ producto_id: '', unidad_medida_id: '', cantidad: '1', costo_unitario: '0' })
const useOptions = (key: string, endpoint: string) => useQuery({ queryKey: [key], queryFn: async () => (await api.get<Paginated<Option>>(endpoint, { params: { page_size: 100 } })).data.results })

export function MovementsPage() {
  const queryClient = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ tipo: 'purchase', sucursal_id: '', almacen_id: '', almacen_origen_id: '', almacen_destino_id: '', proveedor_id: '', referencia: '', observacion: '' })
  const [items, setItems] = useState<Item[]>([emptyItem()])
  const branches = useOptions('branch-options', '/core/sucursales/')
  const warehouses = useOptions('warehouse-options', '/inventory/almacenes/')
  const suppliers = useOptions('supplier-options', '/inventory/proveedores/')
  const products = useOptions('product-options', '/inventory/productos/')
  const units = useOptions('unit-options', '/inventory/unidades-medida/')
  const create = useMutation({ mutationFn: () => api.post('/inventory/movimientos/', { ...form, operation_id: crypto.randomUUID(), sucursal_id: Number(form.sucursal_id), almacen_id: form.almacen_id ? Number(form.almacen_id) : undefined, almacen_origen_id: form.almacen_origen_id ? Number(form.almacen_origen_id) : undefined, almacen_destino_id: form.almacen_destino_id ? Number(form.almacen_destino_id) : undefined, proveedor_id: form.proveedor_id ? Number(form.proveedor_id) : undefined, items: items.map((item) => ({ producto_id: Number(item.producto_id), unidad_medida_id: Number(item.unidad_medida_id), cantidad: Number(item.cantidad), ...(form.tipo === 'purchase' ? { costo_unitario: Number(item.costo_unitario) } : {}) })) }), onSuccess: async () => { setOpen(false); setItems([emptyItem()]); await queryClient.invalidateQueries({ queryKey: ['movements'] }) } })
  const updateItem = (index: number, key: keyof Item, value: string) => setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item))
  const submit = (event: FormEvent) => { event.preventDefault(); if (!create.isPending) create.mutate() }
  return <><PageHeader eyebrow="Inventario" title="Movimientos" description="Compras, salidas y traslados ejecutados por el servicio transaccional; la UI nunca modifica stock." actions={<PermissionGate permission="inventory.movimientos.create"><button className="button button--primary" onClick={() => setOpen(true)}>Registrar movimiento</button></PermissionGate>} />
    <section className="panel table-panel"><ResourceTable<Movement> endpoint="/inventory/movimientos/" queryKey="movements" columns={[
      { key: 'id', label: 'N.º' }, { key: 'tipo', label: 'Tipo', render: (row) => <span className="badge badge--info">{labels[row.tipo] ?? row.tipo}</span> }, { key: 'referencia', label: 'Referencia' }, { key: 'almacen_origen', label: 'Origen' }, { key: 'almacen_destino', label: 'Destino' }, { key: 'created_at', label: 'Fecha', render: (row) => new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(row.created_at)) },
    ]} /></section>
    <Modal open={open} title="Registrar movimiento" onClose={() => !create.isPending && setOpen(false)}><form onSubmit={submit}><div className="form-grid"><label>Tipo<select value={form.tipo} onChange={(event) => setForm({ ...form, tipo: event.target.value })}><option value="purchase">Compra</option><option value="output">Salida</option><option value="transfer">Traslado</option></select></label><label>Sucursal<select required value={form.sucursal_id} onChange={(event) => setForm({ ...form, sucursal_id: event.target.value })}><option value="">Selecciona…</option>{branches.data?.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label>
      {form.tipo !== 'transfer' && <label>Almacén<select required value={form.almacen_id} onChange={(event) => setForm({ ...form, almacen_id: event.target.value })}><option value="">Selecciona…</option>{warehouses.data?.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label>}{form.tipo === 'transfer' && <><label>Almacén origen<select required value={form.almacen_origen_id} onChange={(event) => setForm({ ...form, almacen_origen_id: event.target.value })}><option value="">Selecciona…</option>{warehouses.data?.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label><label>Almacén destino<select required value={form.almacen_destino_id} onChange={(event) => setForm({ ...form, almacen_destino_id: event.target.value })}><option value="">Selecciona…</option>{warehouses.data?.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label></>}{form.tipo === 'purchase' && <label>Proveedor<select required value={form.proveedor_id} onChange={(event) => setForm({ ...form, proveedor_id: event.target.value })}><option value="">Selecciona…</option>{suppliers.data?.map((item) => <option key={item.id} value={item.id}>{item.razon_social}</option>)}</select></label>}<label>Referencia<input value={form.referencia} onChange={(event) => setForm({ ...form, referencia: event.target.value })} /></label>{form.tipo === 'output' && <label>Motivo<input value={form.observacion} onChange={(event) => setForm({ ...form, observacion: event.target.value })} /></label>}</div>
      <h3>Productos</h3>{items.map((item, index) => <div className="movement-item" key={index}><label>Producto<select required value={item.producto_id} onChange={(event) => updateItem(index, 'producto_id', event.target.value)}><option value="">Selecciona…</option>{products.data?.map((option) => <option key={option.id} value={option.id}>{option.nombre}</option>)}</select></label><label>Unidad<select required value={item.unidad_medida_id} onChange={(event) => updateItem(index, 'unidad_medida_id', event.target.value)}><option value="">Selecciona…</option>{units.data?.map((option) => <option key={option.id} value={option.id}>{option.nombre}</option>)}</select></label><label>Cantidad<input type="number" required min="0.0001" step="0.0001" value={item.cantidad} onChange={(event) => updateItem(index, 'cantidad', event.target.value)} /></label>{form.tipo === 'purchase' && <label>Costo<input type="number" required min="0" step="0.0001" value={item.costo_unitario} onChange={(event) => updateItem(index, 'costo_unitario', event.target.value)} /></label>}{items.length > 1 && <button type="button" className="link-button" onClick={() => setItems(items.filter((_, itemIndex) => itemIndex !== index))}>Quitar</button>}</div>)}<button type="button" className="button button--ghost" onClick={() => setItems([...items, emptyItem()])}>Agregar producto</button>
      {create.isError && <p className="form-error" role="alert">{apiErrorMessage(create.error)}</p>}<div className="form-actions"><button type="button" className="button button--ghost" onClick={() => setOpen(false)} disabled={create.isPending}>Cancelar</button><button className="button button--primary" disabled={create.isPending}>{create.isPending ? 'Registrando…' : 'Registrar'}</button></div></form></Modal>
  </>
}
